[package]
name = "shurbai"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.80"
llama-cpp-2 = { version = "0.1.27", default-features = false }
rand = "0.8.5"
serde = { version = "1.0", features = ["derive"] }

[features]
# cublas = ["llama-cpp-2/cublas"]
