[package]
name = "shurbai"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.80"
llama-cpp-2 = "0.1.27"
rand = "0.8.5"
serde = { version = "1.0", features = ["derive"] }
